apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gola-api.name" . }}-config
{{- $filepath:= include "gola-api.configpath" . }}
data:
  {{ range $index, $path := .Files.Glob $filepath -}}
  {{ $index | base }}: |
{{ printf "%s" $path | indent 4}}
  {{- end -}}
