apiVersion: v1
kind: Service
metadata:
  name: {{ include "gola-api.name" . }}-svc
spec:
  selector:
    app: {{ include "gola-api.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
